---
title: "R for Data Science"
output: html_notebook
---

```{r}
library(tidyverse)
```

#### 1.2.3
```{r}
ggplot(data = mpg)
```

```{r}
mtcars
```

```{r}
?mpg
```

```{r}
ggplot(mpg) +
   geom_point(mapping = aes(x = hwy, y = cyl))
```

```{r}
ggplot(mpg) +
   geom_point(mapping = aes(x = class, y = drv))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, size = class))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

#### Why all dots are not blue?
```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))
```

```{r}
mpg
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, color = year))
```


```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, size = year))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, shape = year))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, color = year, size = year))
```


```{r}
?geom_point
```
```{r}
# ggplot(data = mpg) +
#    geom_point(mapping = aes(x = displ, y = hwy, stroke = class))
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   geom_point(mapping = aes(x = displ, y = hwy, color = year))
```


```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   facet_wrap(~ class, nrow = 2)
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   facet_grid(drv ~ cyl)
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   facet_grid(. ~ cyl)
```
```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   facet_grid(drv ~ .)
```


#### continuous value
```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   facet_wrap(~ cty)
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = drv, y = cyl))
```



```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   geom_smooth(mapping = aes(x = displ, y = hwy))
```


```{r}
ggplot(data = mpg) +
   geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```


```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy, color = drv)) +
   geom_smooth(mapping = aes(x = displ, y = hwy, color = drv, linetype = drv))
```


```{r}
ggplot(data = mpg) +
   geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
ggplot(data = mpg) +
   geom_smooth(mapping = aes(x = displ, y = hwy, color = drv),
               show.legend = F)
```

```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy)) +
   geom_smooth(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point() +
   geom_smooth()

```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point(mapping = aes(color = class)) +
   geom_smooth()
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point(mapping = aes(color = class)) +
   geom_smooth(
      data = filter(mpg, class == "subcompact"),
      se = F
   )
```


```{r}
ggplot(data = mpg, mapping = aes(group = class)) +
   geom_boxplot(mapping = aes(x = class, y = hwy))
```


```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) +
   geom_point() +
   geom_smooth(se = F)
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point() +
   geom_smooth()
ggplot() +
   geom_point(
      data = mpg, 
      mapping = aes(x = displ, y = hwy)) +
   geom_smooth(
      data = mpg, 
      mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point() +
   geom_smooth(se = F)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point() +
   geom_smooth(mapping = aes(group = drv), se = F)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) +
   geom_point() +
   geom_smooth(se = F)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point(mapping = aes(color = drv)) +
   geom_smooth(se = F)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point(mapping = aes(color = drv)) +
   geom_smooth(mapping = aes(linetype = drv), se = F)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
   geom_point(size = 6, color = "white") +
   geom_point(mapping = aes(color = drv))
```

### 1.7
```{r}
diamonds   
```


```{r}
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut))
```

```{r}
?geom_bar
```

```{r}
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut))
ggplot(data = diamonds) +
   stat_count(mapping = aes(x = cut))
```

```{r}
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
```

```{r}
ggplot(data = diamonds) +
   stat_summary(
      mapping = aes(x = cut, y = depth),
      fun.ymin = min,
      fun.ymax = max,
      fun.y = median
   )
```

```{r}
?stat_summary
```

```{r}
# ggplot(data = diamonds) +
#    geom_pointrange(
#       mapping = aes(x = cut, y = median(depth), ymin = min(depth), 
#                     ymax = max(depth)), group = cut)
```

```{r}
?geom_col
```

```{r}
ggplot(data = diamonds) +
   geom_col(mapping = aes(x = cut, y = price))
```

```{r}
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, y = ..prop..))
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..), 
            show.legend = F)
```


### 1.8
```{r}
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, color = cut))
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, fill = cut))
```

```{r}
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, fill = clarity))
```

```{r}
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, fill = clarity),
            position = "identity")
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, fill = clarity),
            position = "fill")
ggplot(data = diamonds) +
   geom_bar(mapping = aes(x = cut, fill = clarity),
            position = "dodge")
```


```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg) +
   geom_point(mapping = aes(x = displ, y = hwy),
              position = "jitter")
ggplot(data = mpg) +
   geom_jitter(mapping = aes(x = displ, y = hwy))
```

```{r}
?geom_jitter
```


```{r}
ggplot(data = mpg) +
   geom_point(mapping = aes(x = cty, y = hwy))
ggplot(data = mpg) +
   geom_jitter(mapping = aes(x = cty, y = hwy))
ggplot(data = mpg) +
   geom_jitter(mapping = aes(x = cty, y = hwy), width = 1, height = 1)
ggplot(data = mpg) +
   geom_jitter(mapping = aes(x = cty, y = hwy), width = 3, height = 3)
```




### 1.9
```{r}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
   geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
   geom_boxplot() +
   coord_flip()
```

```{r}
bar <- ggplot(data = diamonds) +
   geom_bar(
      mapping = aes(x = cut, fill = cut),
      show.legend = FALSE,
      width = 1
   ) +
   theme(aspect.ratio = 1) +
   labs(x = NULL, y = NULL)
bar + coord_flip()
bar + coord_polar()
```


```{r}
bar <- ggplot(data = diamonds) +
   geom_bar(
      mapping = aes(x = cut, fill = clarity),
      position = "identity"
   )
bar
bar + coord_polar()
```


```{r}
?labs
bar <- ggplot(data = diamonds) +
   geom_bar(
      mapping = aes(x = cut, fill = clarity),
      position = "identity"
   ) +
   labs(x = "CUT", y = "COUNT")
bar + coord_polar()
```


```{r}
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
   geom_point() +
   geom_abline() +
   coord_fixed()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
   geom_point() +
   geom_abline()
```



### 1.10


## 2
### 2.1
### 2.2
### 2.3

大した練習問題なし

## 3
### 3.1
```{r}
library(nycflights13)
library(tidyverse)
```

```{r}
flights
```


### 3.2
```{r}
filter(flights, arr_delay > 120)
```

```{r}
filter(flights, dest %in% c("IAH", "HOU"))
```

```{r}
filter(flights, carrier %in% c("UA", "AA", "DL"))
```

```{r}
filter(flights, month %in% c(7:9))
```

```{r}
filter(flights, arr_delay > 120 & dep_delay <= 0)
```

```{r}
filter(flights, dep_delay >= 60 & dep_delay - arr_delay >= 30 )
```

```{r}
filter(flights, dep_time < 600)
```


```{r}
filter(flights, is.na(dep_time))
```


```{r}
NA ^ 0
NA | TRUE
FALSE & NA
NA * 0
```


### 3.3
```{r}
arrange(flights, desc(is.na(dep_delay)))
```

```{r}
arrange(flights, desc(dep_delay))
```

```{r}
arrange(flights, desc(distance / air_time))
```


```{r}
arrange(flights, distance)
```



### 3.4










